import pandas as pd

records = pd.DataFrame(
    [
        (1, "Großbritannien ist Europas größte Insel."),
        (2, "Die Alpen sind das höchste Gebirge Europas."),
        (3, "Längster Fluß ist die Wolga. Sie mündet in das Kaspisches Meer."),
        (4, "Moskau ist die größte Stadt Europas."),
        (5, "Der höchste Vulkan ist der 3340 m hohe Ätna."),
        (6, "Am Bosporus liegt Istanbul. Es ist die einzige Stadt, die gleichzeitig auf zwei verschiedenen Kontinenten liegt."),
        (7, "Der Ladogasee ist Europas größter See."),
        (8, "Russland ist der größte Staat in Europa."),
        (9, "Das Nordkap ist der nördlichste Punkt des europäischen Festlandes."),
        (10, "Längstes Gebirge sind die Karpaten."),
        (11, "Der Ural gilt als Abgrenzung Europas zu Asien."),
        (12, "Höchster Berg ist der 4807 m hohe Mont Blanc."),
        (13, "Der kleinste Staat ist der Vatikanstaat. Er ist der Sitz des Papst."),
        (14, "Das Mittelmeer verbindet drei Kontinente."),
        (15, "Nach den Flüssen Rhein und Ruhr wird Europas größte Industrie- und Ballungsraum benannt."),
        (16, "Die größte Inselgruppe liegt im Adriatischen Meer."),
        (17, "Die größte Seenplatte findet man in Finnland."),
        (18, "Der bedeutendste Kanal ist der Nord-Ostsee-Kanal."),
        (19, "Europas westlichste Großstadt heißt Lissabon."),
        (20, "Sizilien ist die größte Insel im Mittelmeer."),
        (21, "Kreta ist die südlichste europäische Insel."),
        (22, "An der Straße von Gibraltar ist Europa von Afrika 14 km entfernt."),
        (23, "Der Rhein ist Europas bedeutendste Wasserstraße."),
        (24, "In der Nordsee liegt das größte Erdölvorkommen."),
        (25, "Die Niederlande sind der Staat mit der größten Bevölkerungsdichte."),
        (26, "Am längsten zugefroren ist das Weiße Meer."),
        (27, "Europas zweithöchster Vulkan ist der 1277 m hohe Vesuv."),
        (28, "Deutschlands höchstes Mittelgebirge ist der Schwarzwald."),
        (29, "An der Mündung des Rehins in die Nordsee liegt Rotterdam, der größte Hafen der Welt."),
        (30, "Weit nördlich des Polarkreises liegt Murmansk, Europas nördlichste Großstadt."),
        (31, "Alle Meere rund um Europa gehören zu einem einzigen Ozean: dem Atlanntik."),
        (32, "Die meisten Vulkane und gleichzeitig auch die größten Gletscher gibt es in Island."),
        (33, "Mit 2850 km Länge ist die Donau der zweitlängste Strom in Europa. An ihr liegen 4 Hauptständte"),
        (34, "Die buchtenreichste Küste hat Norwegen vorzuweisen."),
        (35, "Der einzige untermeerische Tunnel verbindet Frankreich und Großebritannien und führt unter dem Ärmelkanal hindurch."),
        (36, "Das Meer nördlich des Polarkreises nennt sich Nordpolarmeer."),
        (37, "Die Ostsee ist das größte Binnenmeer der Erde."),
        (38, "Italien liegt auf der Appenninischen Halbinsel."),
        (39, "Die Balkanischen Halbinsel liegt im Südosten Europas."),
        (40, "Auf der Iberischen Halbinsel liegen Spanien und Portugal.")
    ], columns=["id", "fact"]
).set_index("id")
